// <auto-generated />
using System;
using Carnivorous_Plant_Nursery.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Carnivorous_Plant_Nursery.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260609041838_AddIdentityAuth")]
    partial class AddIdentityAuth
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Carnivorous_Plant_Nursery.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultShippingCity")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Carnivorous_Plant_Nursery.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<bool>("IsAvailableInWebshop")
                        .HasColumnType("bit");

                    b.Property<string>("ListingTitle")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SKU")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Article", t =>
                        {
                            t.HasCheckConstraint("CK_Article_Price_NonNegative", "[Price] >= 0");
                        });

                    b.HasDiscriminator().HasValue("Article");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Carnivorous_Plant_Nursery.Models.CareProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CareDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("CareProfileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MaxTemperature")
                        .HasColumnType("int");

                    b.Property<int?>("MinTemperature")
                        .HasColumnType("int");

                    b.Property<int?>("RequiredHumidity")
                        .HasColumnType("int");

                    b.Property<int?>("RequiredLight")
                        .HasColumnType("int");

                    b.Property<bool?>("RequiresWinterDormancy")
                        .HasColumnType("bit");

                    b.Property<string>("SoilMix")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TemperatureDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("CareProfile");
                });

            modelBuilder.Entity("Carnivorous_Plant_Nursery.Models.Lineage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("FatherId")
                        .HasColumnType("int");

                    b.Property<string>("Generation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GeneticsDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool?>("IsClone")
                        .HasColumnType("bit");

                    b.Property<int?>("MotherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FatherId");

                    b.HasIndex("MotherId");

                    b.ToTable("Lineage");
                });

            modelBuilder.Entity("Carnivorous_Plant_Nursery.Models.Taxonomy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CareProfileId")
                        .HasColumnType("int");

                    b.Property<string>("CommonName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Cultivar")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Genus")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Species")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CareProfileId");

                    b.ToTable("Taxonomy");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Carnivorous_Plant_Nursery.Models.InventoryItem", b =>
                {
                    b.HasBaseType("Carnivorous_Plant_Nursery.Models.Article");

                    b.Property<DateTime?>("DateAcquired")
                        .HasColumnType("datetime2");

                    b.Property<string>("InternalNotes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("LineageId")
                        .HasColumnType("int");

                    b.Property<string>("LocationInNursery")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("TaxonomyId")
                        .HasColumnType("int");

                    b.HasIndex("LineageId");

                    b.HasIndex("TaxonomyId");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_Article_Price_NonNegative", "[Price] >= 0");
                        });

                    b.HasDiscriminator().HasValue("InventoryItem");
                });

            modelBuilder.Entity("Carnivorous_Plant_Nursery.Models.Plant", b =>
                {
                    b.HasBaseType("Carnivorous_Plant_Nursery.Models.InventoryItem");

                    b.Property<int?>("CurrentStage")
                        .HasColumnType("int");

                    b.Property<int?>("EstimatedAgeAtAcquiryYears")
                        .HasColumnType("int");

                    b.Property<string>("HealthDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("HealthStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastDormancyDateEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastDormancyDateStart")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastRepottingDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("PotDiameterCm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PotHeightCm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("SourceSeedBatchId")
                        .HasColumnType("int");

                    b.HasIndex("SourceSeedBatchId");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_Article_Price_NonNegative", "[Price] >= 0");

                            t.HasCheckConstraint("CK_Plant_EstimatedAgeAtAcquiryYears_NonNegative", "[EstimatedAgeAtAcquiryYears] >= 0");

                            t.HasCheckConstraint("CK_Plant_PotDiameterCm_NonNegative", "[PotDiameterCm] >= 0");

                            t.HasCheckConstraint("CK_Plant_PotHeightCm_NonNegative", "[PotHeightCm] >= 0");
                        });

                    b.HasDiscriminator().HasValue("Plant");
                });

            modelBuilder.Entity("Carnivorous_Plant_Nursery.Models.SeedBatch", b =>
                {
                    b.HasBaseType("Carnivorous_Plant_Nursery.Models.InventoryItem");

                    b.Property<decimal?>("EstimatedGerminationRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ExpectedViabilityMonths")
                        .HasColumnType("int");

                    b.Property<DateTime?>("HarvestDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("RequiresStratification")
                        .HasColumnType("bit");

                    b.Property<int?>("SeedCount")
                        .HasColumnType("int");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_Article_Price_NonNegative", "[Price] >= 0");

                            t.HasCheckConstraint("CK_SeedBatch_EstimatedGerminationRate_Range", "[EstimatedGerminationRate] >= 0 AND [EstimatedGerminationRate] <= 1");

                            t.HasCheckConstraint("CK_SeedBatch_SeedCount_NonNegative", "[SeedCount] >= 0");
                        });

                    b.HasDiscriminator().HasValue("SeedBatch");
                });

            modelBuilder.Entity("Carnivorous_Plant_Nursery.Models.Lineage", b =>
                {
                    b.HasOne("Carnivorous_Plant_Nursery.Models.InventoryItem", "Father")
                        .WithMany()
                        .HasForeignKey("FatherId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Carnivorous_Plant_Nursery.Models.InventoryItem", "Mother")
                        .WithMany()
                        .HasForeignKey("MotherId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Father");

                    b.Navigation("Mother");
                });

            modelBuilder.Entity("Carnivorous_Plant_Nursery.Models.Taxonomy", b =>
                {
                    b.HasOne("Carnivorous_Plant_Nursery.Models.CareProfile", "CareProfile")
                        .WithMany("Taxonomies")
                        .HasForeignKey("CareProfileId");

                    b.Navigation("CareProfile");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Carnivorous_Plant_Nursery.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Carnivorous_Plant_Nursery.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Carnivorous_Plant_Nursery.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Carnivorous_Plant_Nursery.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Carnivorous_Plant_Nursery.Models.InventoryItem", b =>
                {
                    b.HasOne("Carnivorous_Plant_Nursery.Models.Lineage", "Lineage")
                        .WithMany()
                        .HasForeignKey("LineageId");

                    b.HasOne("Carnivorous_Plant_Nursery.Models.Taxonomy", "Taxonomy")
                        .WithMany("InventoryItems")
                        .HasForeignKey("TaxonomyId");

                    b.Navigation("Lineage");

                    b.Navigation("Taxonomy");
                });

            modelBuilder.Entity("Carnivorous_Plant_Nursery.Models.Plant", b =>
                {
                    b.HasOne("Carnivorous_Plant_Nursery.Models.SeedBatch", "SourceSeedBatch")
                        .WithMany()
                        .HasForeignKey("SourceSeedBatchId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("SourceSeedBatch");
                });

            modelBuilder.Entity("Carnivorous_Plant_Nursery.Models.CareProfile", b =>
                {
                    b.Navigation("Taxonomies");
                });

            modelBuilder.Entity("Carnivorous_Plant_Nursery.Models.Taxonomy", b =>
                {
                    b.Navigation("InventoryItems");
                });
#pragma warning restore 612, 618
        }
    }
}
