// <auto-generated />
using System;
using Carnivorous_Plant_Nursery.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Carnivorous_Plant_Nursery.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260507101015_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Carnivorous_Plant_Nursery.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<bool>("IsAvailableInWebshop")
                        .HasColumnType("bit");

                    b.Property<string>("ListingTitle")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SKU")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Article", t =>
                        {
                            t.HasCheckConstraint("CK_Article_Price_NonNegative", "[Price] >= 0");
                        });

                    b.HasDiscriminator().HasValue("Article");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Carnivorous_Plant_Nursery.Models.CareProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CareDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("CareProfileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("MaxTemperature")
                        .HasColumnType("int");

                    b.Property<int?>("MinTemperature")
                        .HasColumnType("int");

                    b.Property<int?>("RequiredHumidity")
                        .HasColumnType("int");

                    b.Property<int?>("RequiredLight")
                        .HasColumnType("int");

                    b.Property<bool?>("RequiresWinterDormancy")
                        .HasColumnType("bit");

                    b.Property<string>("SoilMix")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TemperatureDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("CareProfile");
                });

            modelBuilder.Entity("Carnivorous_Plant_Nursery.Models.Lineage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("FatherId")
                        .HasColumnType("int");

                    b.Property<string>("Generation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("GeneticsDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool?>("IsClone")
                        .HasColumnType("bit");

                    b.Property<int?>("MotherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FatherId");

                    b.HasIndex("MotherId");

                    b.ToTable("Lineage");
                });

            modelBuilder.Entity("Carnivorous_Plant_Nursery.Models.Taxonomy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CareProfileId")
                        .HasColumnType("int");

                    b.Property<string>("CommonName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Cultivar")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Genus")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Species")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CareProfileId");

                    b.ToTable("Taxonomy");
                });

            modelBuilder.Entity("Carnivorous_Plant_Nursery.Models.InventoryItem", b =>
                {
                    b.HasBaseType("Carnivorous_Plant_Nursery.Models.Article");

                    b.Property<DateTime?>("DateAcquired")
                        .HasColumnType("datetime2");

                    b.Property<string>("InternalNotes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("LineageId")
                        .HasColumnType("int");

                    b.Property<string>("LocationInNursery")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("TaxonomyId")
                        .HasColumnType("int");

                    b.HasIndex("LineageId");

                    b.HasIndex("TaxonomyId");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_Article_Price_NonNegative", "[Price] >= 0");
                        });

                    b.HasDiscriminator().HasValue("InventoryItem");
                });

            modelBuilder.Entity("Carnivorous_Plant_Nursery.Models.Plant", b =>
                {
                    b.HasBaseType("Carnivorous_Plant_Nursery.Models.InventoryItem");

                    b.Property<int?>("CurrentStage")
                        .HasColumnType("int");

                    b.Property<int?>("EstimatedAgeAtAcquiryYears")
                        .HasColumnType("int");

                    b.Property<string>("HealthDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int?>("HealthStatus")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastDormancyDateEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastDormancyDateStart")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastRepottingDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("PotDiameterCm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PotHeightCm")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_Article_Price_NonNegative", "[Price] >= 0");

                            t.HasCheckConstraint("CK_Plant_EstimatedAgeAtAcquiryYears_NonNegative", "[EstimatedAgeAtAcquiryYears] >= 0");

                            t.HasCheckConstraint("CK_Plant_PotDiameterCm_NonNegative", "[PotDiameterCm] >= 0");

                            t.HasCheckConstraint("CK_Plant_PotHeightCm_NonNegative", "[PotHeightCm] >= 0");
                        });

                    b.HasDiscriminator().HasValue("Plant");
                });

            modelBuilder.Entity("Carnivorous_Plant_Nursery.Models.SeedBatch", b =>
                {
                    b.HasBaseType("Carnivorous_Plant_Nursery.Models.InventoryItem");

                    b.Property<decimal?>("EstimatedGerminationRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ExpectedViabilityMonths")
                        .HasColumnType("int");

                    b.Property<DateTime?>("HarvestDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("RequiresStratification")
                        .HasColumnType("bit");

                    b.Property<int?>("SeedCount")
                        .HasColumnType("int");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_Article_Price_NonNegative", "[Price] >= 0");

                            t.HasCheckConstraint("CK_SeedBatch_EstimatedGerminationRate_Range", "[EstimatedGerminationRate] >= 0 AND [EstimatedGerminationRate] <= 1");

                            t.HasCheckConstraint("CK_SeedBatch_SeedCount_NonNegative", "[SeedCount] >= 0");
                        });

                    b.HasDiscriminator().HasValue("SeedBatch");
                });

            modelBuilder.Entity("Carnivorous_Plant_Nursery.Models.Lineage", b =>
                {
                    b.HasOne("Carnivorous_Plant_Nursery.Models.InventoryItem", "Father")
                        .WithMany()
                        .HasForeignKey("FatherId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Carnivorous_Plant_Nursery.Models.InventoryItem", "Mother")
                        .WithMany()
                        .HasForeignKey("MotherId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Father");

                    b.Navigation("Mother");
                });

            modelBuilder.Entity("Carnivorous_Plant_Nursery.Models.Taxonomy", b =>
                {
                    b.HasOne("Carnivorous_Plant_Nursery.Models.CareProfile", "CareProfile")
                        .WithMany("Taxonomies")
                        .HasForeignKey("CareProfileId");

                    b.Navigation("CareProfile");
                });

            modelBuilder.Entity("Carnivorous_Plant_Nursery.Models.InventoryItem", b =>
                {
                    b.HasOne("Carnivorous_Plant_Nursery.Models.Lineage", "Lineage")
                        .WithMany()
                        .HasForeignKey("LineageId");

                    b.HasOne("Carnivorous_Plant_Nursery.Models.Taxonomy", "Taxonomy")
                        .WithMany("InventoryItems")
                        .HasForeignKey("TaxonomyId");

                    b.Navigation("Lineage");

                    b.Navigation("Taxonomy");
                });

            modelBuilder.Entity("Carnivorous_Plant_Nursery.Models.CareProfile", b =>
                {
                    b.Navigation("Taxonomies");
                });

            modelBuilder.Entity("Carnivorous_Plant_Nursery.Models.Taxonomy", b =>
                {
                    b.Navigation("InventoryItems");
                });
#pragma warning restore 612, 618
        }
    }
}
